#%RAML 1.0

title: Sink Metadata Processing
baseUri: http://api.example.com/x-nmos/sink-mp/{version}
version: v1.0
mediaType: application/json

/:
  displayName: Base
  get:
    description: List of resources available from this API - senders, receivers, and sinks. Each are compulsory parts of the spec.
    responses:
      200:
        body:
          example: !include ../examples/base-get-200.json
          type: !include schemas/sink-api-base.json

/senders:
  displayName: Senders
  get:
    description: Sender root
    responses:
      200:
        description: List EDID Processing compatible Senders. All UUIDs are appended with / to indicate that the ID forms part of the URL for the next layer down.
        body:
          example: !include ../examples/resourcelist-get-200.json
          type: !include schemas/resource-list.json
  /{senderId}:
    get:
      description: List all the API endpoints for a single sender.
      responses:
        200:
          description: Returned when success.
          body:
            example: !include ../examples/sender-get-200.json
            type: !include schemas/sender-base.json
        404:
          description: Returned when the requested Sender ID does not exist.
    /media-profiles:
      get:
        description: Show the last media profile array put before.
        responses:
          200:
            body:
              example: !include ../examples/media-profiles-get-200.json
              type: !include schemas/media_profiles.json
          205:
            description: Denotes an external change occurred which violated the previous Media Profiles.
          404:
            description: Returned when the requested Sender ID does not exist.
      put:
        description: Put desired media profiles.
        body:
          example: !include ../examples/media-profiles-get-200.json
          type: !include schemas/media_profiles.json
        responses:
          200:
            description: Returned when a request is accepted and changes are immediately applied.
            body:
              example: !include ../examples/media-profiles-get-200.json
              type: !include schemas/media_profiles.json
          202:
            description: Returned when a request is accepted and changes can't be immediately applied.
            body:
              example: !include ../examples/media-profiles-get-200.json
              type: !include schemas/media_profiles.json
          400:
            description: >
              Returned when the media profiles are rejected due to schema validation failure or if the Device doesn't support the requested mode.
          404:
            description: Returned when the requested Sender ID does not exist.
          423:
            description: >
              Returned when the media profiles can't be applied temporarily (e.g. due to an existing connection).
          500:
            description: >
              Returned if the media profiles can't be applied due to a reason which is not related to a violation of schema.
            body:
              type: !include schemas/error.json
      delete:
        description: Delete the last media profile array put before.
        responses:
          204:
            description: Returned when success. No body is included.
          404:
            description: Returned when the requested Sender ID does not exist.
          500:
            description: >
              Returned if the media profiles can't delete due to a reason which is not related to a violation of schema.
            body:
              type: !include schemas/error.json
/receivers:
  displayName: Receivers
  get:
    description: List Sink processing compatible Receivers. All UUIDs are appended with / to indicate that the ID forms part of the URL for the next layer down.
    responses:
      200:
        body:
          example: !include ../examples/resourcelist-get-200.json
          type: !include schemas/resource-list.json
  /{receiverId}:
    get:
      description: List all the API endpoints for a single receiver.
      responses:
        200:
          description: Returned when success.
          body:
            example: !include ../examples/receiver-get-200.json
            type: !include schemas/receiver-base.json
        404:
          description: Returned when the requested Receiver ID does not exist.
    /sinks:
      get:
        responses:
          200:
            description: List of Sinks connected to the Receiver.
            body:
              example: !include ../examples/idlist-get-200.json
              type: !include schemas/id-list.json
          404:
            description: Returned when the requested Receiver ID does not exist.
/sinks:
  displayName: Sinks
  get:
    responses:
      200:
        description: List of Sinks connected to the Receiver.
        body:
          example: !include ../examples/resourcelist-get-200.json
          type: !include schemas/resource-list.json
  /{sinkId}:
    get:
      description: List all the API endpoints for a single Sink.
      responses:
        200:
          description: Returned when success.
          body:
            example: !include ../examples/sink-get-200.json
            type: !include schemas/sink-base.json
        404:
          description: Returned when the requested Sink ID does not exist.
    /properties:
      get:
        description: Return properties of Sink.
        responses:
          200:
            description: Returned when success.
            body:
              example: !include ../examples/sink-properties-get-200.json
              type: !include schemas/sink.json
          404:
            description: Returned when the requested Sink ID does not exist.
    /edid:
      get:
        description: >
          Redirects to the location of the EDID file or returns the EDID file directly.
          Check HTTP response code to determine which mode of operation is in use. When returning the EDID file
          directly ensure that the `Content-Type` entity header is correctly set.
        responses:
          200:
            description: The EDID file itself will be served
            body:
              application/octet-stream:
                type: file
          307:
            description: A temporary redirect to the EDID file
          404:
            description: >
              Returned when the EDID file or the requested Sink ID doesn't exist.
